"""ICARTT v1001 export for hyplan flight plans.

ICARTT is the standard text format used by NASA airborne science
missions for archived data. We emit a planned-track file by linearly
interpolating along the flight plan at a configurable interval.
"""

from __future__ import annotations

import datetime

import geopandas as gpd

from ._common import _compute_sza, extract_waypoints

__all__ = ["to_icartt"]


def to_icartt(
    plan: gpd.GeoDataFrame,
    filepath: str,
    pi_name: str = "",
    institution: str = "",
    mission_name: str = "",
    flight_date: datetime.date | None = None,
    aircraft=None,
    takeoff_time: datetime.datetime | None = None,
    interval_seconds: float = 60.0,
    revision: str = "RA",
    revision_comments: str = "RA: Planned flight track - pre-flight",
    special_comments: str = "",
    normal_comments: str = "",
) -> None:
    """Write an ICARTT v1001 file.

    Matches the MovingLines ``save2ict`` / ``write_ict`` format.  Data
    is linearly interpolated along the flight plan at *interval_seconds*
    intervals.

    Args:
        plan: Flight plan GeoDataFrame.
        filepath: Output ``.ict`` path.
        pi_name: Principal investigator name.
        institution: PI institution.
        mission_name: Campaign name.
        flight_date: Flight date (default today).
        aircraft: Aircraft object (for platform name).
        takeoff_time: UTC takeoff time.  If *None*, Start_UTC begins at 0.
        interval_seconds: Interpolation interval in seconds (default 60).
        revision: Revision code (RA, RB, R0, R1, ...).
        revision_comments: Revision description string.
        special_comments: Additional special comment lines.
        normal_comments: Additional normal comment lines.
    """
    if flight_date is None:
        flight_date = datetime.date.today()
    today = datetime.date.today()

    if takeoff_time:
        base_seconds = (takeoff_time.hour * 3600
                        + takeoff_time.minute * 60
                        + takeoff_time.second)
    else:
        base_seconds = 0.0  # type: ignore[assignment]

    # Interpolate along the flight plan
    wps = extract_waypoints(plan)
    interp_points = []  # (utc_s, lat, lon, alt_m, speed_mps, bearing)

    for idx in range(len(wps) - 1):
        w0 = wps.iloc[idx]
        w1 = wps.iloc[idx + 1]

        t0 = base_seconds + w0["cum_time_min"] * 60.0
        t1 = base_seconds + w1["cum_time_min"] * 60.0
        dt = t1 - t0
        if dt <= 0:
            continue

        n_steps = max(1, int(dt / interval_seconds))
        for step in range(n_steps):
            frac = step / n_steps
            t = t0 + frac * dt
            lat = w0["lat"] + frac * (w1["lat"] - w0["lat"])
            lon = w0["lon"] + frac * (w1["lon"] - w0["lon"])
            alt = (w0["alt_m"] or 0) + frac * ((w1["alt_m"] or 0) - (w0["alt_m"] or 0))
            spd = w0["speed_mps"] + frac * (w1["speed_mps"] - w0["speed_mps"])
            hdg = w0["heading"]  # heading for this leg
            interp_points.append((t, lat, lon, alt, spd, hdg))

    # Add final point
    if len(wps) > 0:
        wf = wps.iloc[-1]
        tf = base_seconds + wf["cum_time_min"] * 60.0
        interp_points.append((
            tf, wf["lat"], wf["lon"], wf["alt_m"] or 0,
            0.0, wf["heading"],
        ))

    # Compute SZA for each point
    data_rows = []
    for t, lat, lon, alt, spd, hdg in interp_points:
        if takeoff_time:
            dt_utc = datetime.datetime(
                flight_date.year, flight_date.month, flight_date.day,
                tzinfo=datetime.timezone.utc,
            ) + datetime.timedelta(seconds=t)
            sza = _compute_sza(lat, lon, dt_utc)
        else:
            sza = -9999.0
        data_rows.append((t, lat, lon, alt, spd, hdg, sza))

    # Build header
    platform_name = ""
    if aircraft:
        platform_name = getattr(aircraft, "aircraft_type", "")

    special_lines = [s for s in special_comments.strip().split("\n") if s]
    normal_lines_list = []
    normal_lines_list.append(f"PI_CONTACT_INFO: {pi_name}")
    normal_lines_list.append(f"PLATFORM: {platform_name}")
    normal_lines_list.append("LOCATION: N/A")
    normal_lines_list.append("ASSOCIATED_DATA: N/A")
    normal_lines_list.append("INSTRUMENT_INFO: Planned flight track generated by hyplan")
    normal_lines_list.append("DATA_INFO: Linearly interpolated planned flight track")
    normal_lines_list.append("UNCERTAINTY: N/A - planned track")
    normal_lines_list.append("ULOD_FLAG: -7777")
    normal_lines_list.append("ULOD_VALUE: N/A")
    normal_lines_list.append("LLOD_FLAG: -8888")
    normal_lines_list.append("LLOD_VALUE: N/A")
    normal_lines_list.append(f"DM_CONTACT_INFO: {pi_name}")
    normal_lines_list.append(f"PROJECT_INFO: {mission_name}")
    normal_lines_list.append("STIPULATIONS_ON_USE: Use as-is for flight planning only")
    normal_lines_list.append(f"OTHER_COMMENTS: {normal_comments}")
    normal_lines_list.append(f"REVISION: {revision}")
    normal_lines_list.append(revision_comments)

    n_data_vars = 6  # Lat, Lon, Alt, speed, Bearing, SZA
    n_special = len(special_lines)
    n_normal = len(normal_lines_list)

    # Count header lines: top metadata (7) + interval (1) + indep var (1)
    # + n_data (1) + scale factors (1) + missing values (1)
    # + var descriptions (n_data_vars) + n_special header (1) + special lines
    # + n_normal header (1) + normal lines + column header (1)
    n_header = (7 + 1 + 1 + 1 + 1 + 1 + n_data_vars
                + 1 + n_special + 1 + n_normal + 1)

    header = []
    header.append(f"{n_header}, 1001")
    header.append(pi_name or "N/A")
    header.append(institution or "N/A")
    header.append("Planned flight track - hyplan")
    header.append(mission_name or "N/A")
    header.append("1, 1")
    header.append(f"{flight_date.year}, {flight_date.month}, {flight_date.day}, "
                  f"{today.year}, {today.month}, {today.day}")
    header.append("0")  # data interval (0 = variable)
    header.append("Start_UTC, seconds, seconds from midnight UTC")
    header.append(str(n_data_vars))
    header.append(", ".join(["1"] * n_data_vars))  # scale factors
    header.append(", ".join(["-9999"] * n_data_vars))  # missing values
    header.append("Latitude, Degrees, North positive, geodetic latitude")
    header.append("Longitude, Degrees, East positive, geodetic longitude")
    header.append("Altitude, meters, above sea level")
    header.append("speed, meters per second, ground speed")
    header.append("Bearing, degrees, degrees from north")
    header.append("SZA, degrees, solar zenith angle")
    header.append(str(n_special))
    header.extend(special_lines)
    header.append(str(n_normal))
    header.extend(normal_lines_list)
    header.append("Start_UTC, Latitude, Longitude, Altitude, speed, Bearing, SZA")

    with open(filepath, "w") as f:
        for line in header:
            f.write(line + "\n")
        for t, lat, lon, alt, spd, hdg, sza in data_rows:
            f.write(f"{t:.0f}, {lat:.9f}, {lon:.9f}, {alt:.0f}, "
                    f"{spd:.3f}, {hdg:.3f}, {sza:.3f}\n")
