name: hyplan
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - numpy
  - pandas
  - matplotlib
  - networkx
  - tabulate
  - geopandas
  - shapely
  - pyproj
  - rtree
  - gdal
  - pint
  - pydantic
  - requests
  - folium
  - pymap3d
  - pip
  - pip:
      - pydantic-pint
      - simplekml
      - skyfield
      - sunposition
      - dubins
