name: hyplan
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - folium
  - geopandas
  - gpxpy
  - matplotlib
  - networkx
  - numpy
  - pandas
  - pint
  - pymap3d
  - pyproj
  - rasterio
  - requests
  - rtree
  - shapely
  - timezonefinder
  - xlsxwriter
  - pip
  - pip:
      - simplekml
      - skyfield
