name: hyplan
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - pandas
  - matplotlib
  - networkx
  - geopandas
  - shapely
  - pyproj
  - rtree
  - gdal
  - pint
  - requests
  - folium
  - pymap3d
  - geomag
  - gpxpy
  - xlsxwriter
  - pip
  - pip:
      - simplekml
      - skyfield
      - sunposition
