"""Aircraft performance model and concrete aircraft definitions.

Core definitions live in :mod:`hyplan.aircraft._base`.  Concrete aircraft
subclasses live in :mod:`hyplan.aircraft._models`.  This package re-exports
both so that ``from hyplan.aircraft import Aircraft, NASA_GV`` continues
to work.
"""

from ._base import (
    Aircraft,
    ApproachProfile,
    CasMachSchedule,
    ClimbOutPolicy,
    ClimbPlan,
    PerformanceConfidence,
    PhaseBankAngles,
    SourceRecord,
    SpeedSchedule,
    TasSchedule,
    TurnModel,
    VerticalProfile,
)
from ._models import (
    DLR_HALO,
    NASA_B777,
    NASA_C20A,
    NASA_C130,
    NASA_ER2,
    NASA_GIII,
    NASA_GIV,
    NASA_GV,
    NASA_P3,
    NASA_WB57,
    NCAR_GV,
    NERC_DO228,
    NOAA_GIV,
    NOAA_WP3D,
    SAFIRE_ATR42,
    AWI_BaslerBT67,
    BAS_TwinOtter,
    FAAM_BAe146,
    KingAir350,
    KingAirA90,
    KingAirB200,
    NOAA_TwinOtter,
)
from ._planned_sortie import (
    PlannedSortie,
    load_planned_sortie,
    parse_green_card_pdf,
    parse_green_card_xlsx,
    parse_kml,
)
from ._profile_io import (
    dump_aircraft_profile,
    load_aircraft_profile,
    profile_path,
    write_calibrated_profile,
)
from .iwg1 import load_iwg1, split_iwg1_alltracks, trim_ground_taxi
from .wind_path import climb_with_wind_field, descend_with_wind_field

__all__ = [
    "DLR_HALO",
    "NASA_B777",
    "NASA_C20A",
    "NASA_C130",
    "NASA_ER2",
    "NASA_GIII",
    "NASA_GIV",
    "NASA_GV",
    "NASA_P3",
    "NASA_WB57",
    "NCAR_GV",
    "NERC_DO228",
    "NOAA_GIV",
    "NOAA_WP3D",
    "SAFIRE_ATR42",
    "AWI_BaslerBT67",
    "Aircraft",
    "ApproachProfile",
    "BAS_TwinOtter",
    "CasMachSchedule",
    "ClimbOutPolicy",
    "ClimbPlan",
    "FAAM_BAe146",
    "KingAir350",
    "KingAirA90",
    "KingAirB200",
    "NOAA_TwinOtter",
    "PerformanceConfidence",
    "PhaseBankAngles",
    "PlannedSortie",
    "SourceRecord",
    "SpeedSchedule",
    "TasSchedule",
    "TurnModel",
    "VerticalProfile",
    "dump_aircraft_profile",
    "load_aircraft_profile",
    "load_iwg1",
    "load_planned_sortie",
    "parse_green_card_pdf",
    "parse_green_card_xlsx",
    "parse_kml",
    "profile_path",
    "split_iwg1_alltracks",
    "trim_ground_taxi",
    "write_calibrated_profile",
]
